### ISSUE TITLE
record income or statement payments manually

### ISSUE THREAD

**Issue by rajexcited** [rajexcited/personal-finance-ui#3]
**TODO**
User can manually add following similar to expenses

- [ ] salary
- [ ] passive incomes such as interests from savings accounts
- [ ] credit card bill payment
- [ ] business income
- [ ] other types of incomes active or passive
